version: '3.5'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - '/Users/shipsy/codingwork/nestjs-course/data:/var/lib/postgresql/data'
    ports:
      - '5433:5432'
  node:
    build: .
    ports: 
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'

